version: '3'

services:
  backend:
    build:
      context: ./Back
    depends_on:
      - database
  frontend:
    build:
      context: ./Front
    depends_on:
      - backend
  proxy:
    build:
      context: ./proxy
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
  database:
    image: mysql:5.7
    ports:
      - 3340:3306
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ticketReservation
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
volumes:
  db_volume:
